syntax enable
set background=dark
colorscheme desert

" Numbering
set number
highlight LineNr ctermfg=grey

set tabstop=2       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=2    " Indents will have a width of 4

set softtabstop=2   " Sets the number of columns for a TAB

set expandtab       " Expand TABs to spaces


" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'itchyny/lightline.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'valloric/youcompleteme'
Plug 'sheerun/vim-polyglot'
Plug 'Yggdroot/indentLine'
Plug 'raimondi/delimitmate'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" IndentLine properties/mappings
:nnoremap ilt :IndentLinesToggle<enter>
let g:indentLine_color_term = 236
let g:indentLine_bgcolor_gui = '#00FFFFFF'

" NERDTree properties/mappings
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
:nnoremap nt :NERDTree<enter>
:nnoremap ntt :NERDTreeToggle<enter>
:nnoremap ntf :NERDTreeFocus<enter>

" FZF properties/mappings
:nnoremap fzf :FZF<enter>

" Insert mode mappings
:imap <c-dd> <esc>ddi

